- name: Update and upgrade apt packages
  become: true
  ansible.builtin.apt:
    update_cache: yes
    upgrade: yes
    cache_valid_time: 86400
  when: choice_upgrade_distro | lower == "y"

- name: Install base packages
  become: true
  ansible.builtin.apt:
    name:
      - build-essential
      - pkg-config
      - libncursesw5-dev
      - libreadline-dev
      - curl
      - wget
      - unzip
      - git
      - git-flow
      - tmux
      - vim
      - cargo
    state: present
